# visdrone_custom.yaml
# 数据集路径配置 (建议使用相对路径)
path: ../../datasets/Visdrone # 数据集根目录
train: VisDrone2019-DET-train/images # 训练集
val: VisDrone2019-DET-val/images # 验证集
test: VisDrone2019-DET-test-dev/images # 测试集 (用于最终评估)

# 类别数量
nc: 10

# 类别名称
names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor
